TEXT_ID = 0


def text_id():
    global TEXT_ID
    TEXT_ID += 1
    return TEXT_ID


DEFAULT = text_id()

# Default response text
INTENT_PROCESSING_ERROR = text_id()

# Default intents
INTENT_EMPTY_NAME = text_id()
INTENT_FALLBACK_NAME = text_id()
INTENT_FALLBACK_TEXT = text_id()
INTENT_HELP_NAME = text_id()
INTENT_HELP_TEXT = text_id()
INTENT_GUIDE_NAME = text_id()
INTENT_GUIDE_TEXT = text_id()
INTENT_GUIDE_CONTINUE_TEXT = text_id()
INTENT_GUIDE_CONTINUE_CONFIRM_TEXT = text_id()
INTENT_GUIDE_OPTIONS = text_id()
INTENT_GUIDE_OPTION_NAME = text_id()
INTENT_GUIDE_CONFIRM_NAME = text_id()
INTENT_WELCOME_NAME = text_id()
INTENT_WELCOME_TEXT = text_id()
INTENT_WELCOME_RESUME_TEXT = text_id()
INTENT_WELCOME_YES_TEXT = text_id()
INTENT_WELCOME_NO_TEXT = text_id()
INTENT_WELCOME_CONFIRM_NAME = text_id()
INTENT_WELCOME_DECLINE_NAME = text_id()

# Elicitation intents
INTENT_ELICITATION_SELECT_ARCHITECTURE_NAME = text_id()
INTENT_ELICITATION_SELECT_ARCHITECTURE_TEXT = text_id()
INTENT_ELICITATION_SELECT_COMPONENT_NAME = text_id()
INTENT_ELICITATION_SELECT_COMPONENT_TEXT = text_id()
INTENT_ELICITATION_SELECT_COMPONENT_SERVICE_TEXT = text_id()
INTENT_ELICITATION_SELECT_COMPONENT_OPERATION_TEXT = text_id()
INTENT_ELICITATION_SPECIFY_RESPONSE_NAME = text_id()
INTENT_ELICITATION_SPECIFY_RESPONSE_TEXT = text_id()
INTENT_ELICITATION_SPECIFY_RESPONSE_MEASURE_NAME = text_id()
INTENT_ELICITATION_SPECIFY_RESPONSE_MEASURE_TEXT = text_id()
INTENT_ELICITATION_SAVE_SCENARIO_NAME = text_id()
INTENT_ELICITATION_SAVE_SCENARIO_TEXT = text_id()

# Util intents
INTENT_COMMAND_CONFIG_NAME = text_id()
INTENT_COMMAND_CONFIG_LIST_NAME = text_id()
INTENT_COMMAND_MANAGE_NAME = text_id()
INTENT_COMMAND_MANAGE_LIST_NAME = text_id()

# Extra intents
INTENT_FACT_NAME = text_id()
INTENT_FACT_TEXT = text_id()
INTENT_JOKE_NAME = text_id()
INTENT_JOKE_TEXT = text_id()
