name: Model Tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Test
      run: |
        python ./source/model2arch.py --misim ./resources/models/misim_books.json -vm -va -em -ea temp.js False
        python ./source/model2arch.py --jaeger ./resources/models/jaeger_trace_hotrod.json -vm -va -em -ea temp.json True
        python ./source/model2arch.py --zipkin ./resources/models/zipkin_trace_brave.json -vm -va -em -ea temp.json
